# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loginandregistration', '0002_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Loginandregistration.User'),
        ),
    ]
